# Generated by Django 5.2.6 on 2025-09-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_faculty_department'),
    ]

    operations = [
        # First, rename the old CharField to a temporary name
        migrations.RenameField(
            model_name='faculty',
            old_name='department',
            new_name='department_old',
        ),
        # Then, add the new ForeignKey field
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.department'),
            preserve_default=False,
        ),
        # Finally, remove the old field
        migrations.RemoveField(
            model_name='faculty',
            name='department_old',
        ),
    ]
