# Generated by Django 5.2.6 on 2025-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20250921_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='department_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
