# Generated by Django 5.2.6 on 2025-09-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_faculty_department_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="department_name",
            field=models.CharField(max_length=100),
        ),
    ]
