# Generated by Django 5.2.6 on 2025-09-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_rename_cybersrcurity_department"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
    ]
